@startuml
partition Inspection Staff Supervisor {
:Assign inspections;
}
partition patron {
:View multiple versions of a report/dataset to get both timely and historical information;
}
partition researcher {
:Download reports;
}
partition user {
:Update my profile picture and name so my teammates recognize me;
}
@enduml