@startuml
partition User {
:Create a new folder within my cloud storage;
:Be able to upload files from my computer into a specific folder;
:Be able to download a file or an entire folder to my local device;
:Be able to share a file with another user via a secure link;
}
@enduml