@startuml
skinparam componentStyle uml2
component "Messaging Service" as MessagingService
database "Nosql Database" as NosqlDatabase
database "Redis" as Redis
component "PayPal" <<Component>> as PayPal
NosqlDatabase --> Redis : uses
MessagingService --> Redis : uses
MessagingService --> NosqlDatabase : accesses
MessagingService --> PayPal : integrate with
@enduml