@startuml
skinparam componentStyle uml2
component "Order Service" as OrderService
component "Events Topic" as EventsTopic
component "Kafka" as Kafka
component "Inventory Service" as InventoryService
component "Consumer Group" <<Component>> as ConsumerGroup
interface "Messages" as ifaceMessages
EventsTopic ..> ifaceMessages : use
OrderService ..> ifaceMessages : use
InventoryService ..> ifaceMessages : use
OrderService --> EventsTopic : publish to
InventoryService --> EventsTopic : consume from
InventoryService --> ConsumerGroup : consume via
@enduml