@startuml
skinparam componentStyle uml2
component "Client Ui" <<frontend>> as ClientUi
component "Backend Service" <<backend>> as BackendService
database "MongoDB" as MongoDB
ClientUi --> BackendService : communicates with
BackendService --> MongoDB : accesses
@enduml