@startuml
left to right direction
actor "User" as User
rectangle System {
usecase "Set permissions on a shared file" as Setpermissionsonasharedfile
usecase "Be able to search for files by name or content keywords" as Beabletosearchforfilesbynameorcontentkeywords
}
User --> Setpermissionsonasharedfile
User --> Beabletosearchforfilesbynameorcontentkeywords
@enduml