@startuml
left to right direction
actor "Researcher" as Researcher
actor "User" as User
actor "InspectionStaffSupervisor" as InspectionStaffSupervisor
actor "Patron" as Patron
rectangle System {
usecase "Download reports" as Downloadreports
usecase "Update my profile picture and name" as Updatemyprofilepictureandname
usecase "Assign inspections" as Assigninspections
usecase "View multiple versions of a report/dataset" as Viewmultipleversionsofareportdataset
}
Researcher --> Downloadreports
User --> Updatemyprofilepictureandname
InspectionStaffSupervisor --> Assigninspections
Patron --> Viewmultipleversionsofareportdataset
@enduml