@startuml
participant "Inspection Staff Supervisor" as Inspection_Staff_Supervisor
participant "patron" as patron
participant "researcher" as researcher
participant "user" as user
participant "report" as report
participant "System" as System
researcher -> System: download reports
user -> System: update my profile picture and name so my teammates recognize me
Inspection_Staff_Supervisor -> System: Assign Inspections
patron -> report: view multiple versions of a report/dataset to get both timely and historical information
@enduml