@startuml
participant "Manager" as Manager
participant "Sales Rep" as Sales_Rep
participant "System" as System
participant "User" as User
participant "account" as account
Sales_Rep -> System: be able to set a follow-up reminder for a specific contact
Sales_Rep -> account: view all contacts associated with a specific company (account)
Manager -> System: assign ownership of a lead to a specific Sales Rep
System -> System: send an automated welcome email to a new contact when they are entered into the system
Sales_Rep -> System: mark an opportunity as 'Closed Won' when a deal is finalized
User -> System: be able to export a list of leads for a specific campaign
@enduml