@startuml
skinparam componentStyle uml2
component "Client Ui" <<frontend>> as ClientUi
component "Payment Service" as PaymentService
database "Central Database" as CentralDatabase
interface "Http" as ifaceHttp
PaymentService -- ifaceHttp
ClientUi --> PaymentService : communicates with
PaymentService --> CentralDatabase : accesses
@enduml