@startuml
skinparam componentStyle uml2
component "Mobile App" <<frontend>> as MobileApp
component "Api Service" <<backend>> as ApiService
database "MySQL" as MySQL
MobileApp --> ApiService : communicates with
ApiService --> MySQL : accesses
@enduml